Add integrationType parameter to DiscordStrategyOptions
JonnyBnator/remix-auth-discord pull request #10
Opened 2024-07-31 07:28 UTC by 0x1026

This pull request adds the `integrationType` parameter to the `DiscordStrategyOptions` interface and the `DiscordStrategy` class.

The `integrationType` parameter specifies the installation context for the authorization and is only relevant when the `scope` contains `applications.commands`.

This pull request also includes tests to ensure that the `integrationType` is correctly set and that an error is thrown when it is required but not provided.

2024-08-09 13:55 UTC, JonnyBnator commented
Thank you for your work.

I have added some comments that need to be adressed.
But once that is done, I will happily merge your PR!

2024-08-09 14:52 UTC, 0x1026 commented
Okay, but I don't see the comments 👀

2024-08-09 19:59 UTC, JonnyBnator requested changes
My bad. should be visible now (I hope...)

2024-08-09 19:59 UTC, JonnyBnator commented on src/index.ts
> +    if (scope?.includes("applications.commands") && !integrationType)
This if statement incorrectly evaluates to true if the integrationType is 0 
*(and the scope includes application.commands)*

2024-08-09 19:59 UTC, JonnyBnator commented on src/index.ts
> +  integrationType?: 0 | 1;
I would rather have an enum
`export enum DiscordIntegrationType {
  GUILD_INSTALL = 0,
  USER_INSTALL = 1
}`
that gets used here.
Move your comment explanation to the enum declaration and add a link to the doc
*(like the other type declarations)*

 This will make it easier for the devs to quickly figure out what to do.

2024-08-09 19:59 UTC, JonnyBnator commented on src/index.ts
> +  private integrationType: DiscordStrategyOptions["integrationType"];
Just like the prompt, this is an optional variable.

2024-08-16 12:48 UTC, merged

2024-08-16 12:49 UTC, JonnyBnator commented
Thanks again for your work! :)

2024-08-16 13:47 UTC, 0x1026 commented
It's a pleasure helping with my contributions, also help me using this project as a dependency ^^